### ISSUE TITLE
[RRFC] Add changed callback to Ref

### ISSUE THREAD

**Issue by Christian24** [lit/rfcs#9]
- [x ] I searched for an existing RRFC which might be relevant to my RRFC

Hello everyone,

## Motivation
The `ref` directive is awesome. However, `Ref.value` can always be `undefined`. Recently, I found myself wanting to access `value` only once and only if `Ref.value` was defined. With knowledge of my rendering code I could use `firstUpdated()` instead, but this only works if the element is rendered initially. And the other way, when the element would be no longer rendered would be impossible to detect.   

My use case is wanting to access an element to see if certain `styles` are set - such as `display: none` for example.  

## Example
```ts
let elementRef: Ref<HtmlElement> = createRef((oldValue: HtmlElement | undefined, value: HtmlElement | undefined) => {
// Do something here if the Ref changes.
});
```

## How
https://github.com/lit/lit/blob/0275bd0bf1c96d1e27983cefd6c7c0e5ebe53d2e/packages/lit-html/src/directives/ref.ts#L52 detects already if the `RefElement` changed. So, it should be pretty easy to invoke an optional callback function defined on `Ref` there.

 
### Current Behavior
Nothing. 

### Desired Behavior
The optional callback would invoked whenever the `RefElement` changes. 
## References

* n/a

I dunno. Maybe I am alone with this, but recently, I thought it would be pretty useful. 

Interested to hear what you think,
Christian

**Comment by kevinpschaaf** [comment]
There is already a [callback version of the API](https://lit.dev/docs/templates/directives/#referencing-rendered-dom:~:text=A%20ref%20callback-,can,-also%20be%20passed): you can pass a callback directly to the ref directive instead of a `Ref` object. 

Are you saying you want to pass a `Ref` object _and_ have a callback called when the `ref.value` changes? If you're designing your logic around detecting ref changes via the callback, what's the use case for also having the stateful ref object (rather than just getting the value from the callback argument)?

**Comment by Christian24** [comment]
This might be exactly what I need. 

Sorry, I wasn't aware of this. I will try it tomorrow and let you know if it is sufficient, but I guess so.

**Comment by Christian24** [comment]
This does exactly what I wanted it to. Thanks :)
